### ISSUE TITLE
App freezes after calling getAll(idsList)

### ISSUE THREAD

**Issue by AmaliaMV** [grails/gorm-neo4j#101]
## Description of the Issue

We have a `Person` class and a `User` class. Both classes extend `BaseDomain` class which has a property called `updatedBy` which is a reference to a `User`. That means a `User` can have himself as updatedBy. Also, the `updatedBy` property can be nullable and has some conditions on the mapping.

```
class BaseDomain {

    User updatedBy

    static constraints = {
        updatedBy nullable: true
    }

    static mapping = {
        updatedBy lazy: false, fetch: "eager"
    }

}
```

When we call `getAll()` method with a list of ids as param, the application freezes and we never have the answer.

```
def index() {
        log.info("Executing index controller ...")
        StatementResult result = Person.executeCypher("MATCH (n:test_Person) RETURN ID(n) as id LIMIT ${Person.TOTAL}")

        List ids = new ArrayList<>(Person.TOTAL)

        while (result.hasNext()) {
            Long id = result.next().get("id").asLong()
            ids.add(id)
        }

        log.info("I got ${ids.size()} ids to retrieve ...")
        List people = Person.getAll(ids)   // <--------------------- here we have the issue
        log.info("Retrieved ${people.size()} items. Rendering response")
        render people: people, size: people.size()
}
```

I added a thread report to the repository, but I write here the important part:

```
  java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	  at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
	  at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
	  at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
	  at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	  at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:109)
	  at org.neo4j.driver.internal.InternalStatementResult.blockingGet(InternalStatementResult.java:123)
	  at org.neo4j.driver.internal.InternalStatementResult.hasNext(InternalStatementResult.java:60)
	  at org.grails.datastore.gorm.query.AbstractResultList.<init>(AbstractResultList.java:46)
	  at org.grails.datastore.gorm.query.AbstractResultList.<init>(AbstractResultList.java:36)
	  at org.grails.datastore.gorm.neo4j.collection.Neo4jResultList.<init>(Neo4jResultList.groovy:57)
	  at org.grails.datastore.gorm.neo4j.collection.Neo4jResultList.<init>(Neo4jResultList.groovy:-1)
	  at org.grails.datastore.gorm.neo4j.engine.Neo4jAssociationQueryExecutor.query(Neo4jAssociationQueryExecutor.groovy:240)
	  at org.grails.datastore.gorm.neo4j.engine.Neo4jEntityPersister.unmarshall(Neo4jEntityPersister.java:561)
	  at org.grails.datastore.gorm.neo4j.engine.Neo4jEntityPersister.unmarshallOrFromCache(Neo4jEntityPersister.java:286)
	  at org.grails.datastore.gorm.neo4j.engine.Neo4jEntityPersister.unmarshallOrFromCache(Neo4jEntityPersister.java:268)
	  at org.grails.datastore.gorm.neo4j.engine.Neo4jEntityPersister.unmarshallOrFromCache(Neo4jEntityPersister.java:264)
	  at org.grails.datastore.gorm.neo4j.engine.Neo4jEntityPersister.unmarshallOrFromCache(Neo4jEntityPersister.java:260)
	  at org.grails.datastore.gorm.neo4j.engine.Neo4jEntityPersister.unmarshall(Neo4jEntityPersister.java:456)
	  at org.grails.datastore.gorm.neo4j.engine.Neo4jEntityPersister.unmarshallOrFromCache(Neo4jEntityPersister.java:286)
	  at org.grails.datastore.gorm.neo4j.collection.Neo4jResultList.nextDecodedInternal(Neo4jResultList.groovy:117)
	  at org.grails.datastore.gorm.neo4j.collection.Neo4jResultList.nextDecoded(Neo4jResultList.groovy:94)
	  at org.grails.datastore.gorm.query.AbstractResultList.convertObject(AbstractResultList.java:99)
	  at org.grails.datastore.gorm.query.AbstractResultList$1.next(AbstractResultList.java:183)
	  at org.grails.datastore.mapping.core.AbstractSession.retrieveAll(AbstractSession.java:826)
	  at org.grails.datastore.gorm.GormStaticApi$_getAll_closure12.doCall(GormStaticApi.groovy:387)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1427)
	  at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	  at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	  at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	  at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	  at groovy.lang.Closure.call(Closure.java:418)
	  at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:54)
	  at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:124)
	  at com.sun.proxy.$Proxy91.doInSession(Unknown Source:-1)
	  at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:319)
	  at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:40)
	  at org.grails.datastore.gorm.GormStaticApi.getAll(GormStaticApi.groovy:386)
	  at org.grails.datastore.gorm.GormStaticApi.getAll(GormStaticApi.groovy:377)
	  at org.grails.datastore.gorm.GormEntity$Trait$Helper.getAll(GormEntity.groovy:584)
	  at org.grails.datastore.gorm.GormEntity$Trait$Helper$getAll$5.call(Unknown Source:-1)
	  at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:136)
	  at com.example.Person.getAll(Person.groovy:-1)
	  at com.example.PersonController.index(PersonController.groovy:22)
```
We think that is related with the `updateBy` property.

![image](https://user-images.githubusercontent.com/5392638/50653398-28616e00-0f68-11e9-8108-1cd2a0559f49.png)

Additionally, if you remove `updatedBy lazy: false, fetch: "eager"` line of `BaseDomain` class, the issue doesn't happen.

## Steps to Reproduce

1. Clone https://github.com/AmaliaMV/neo4j-getAll
2. Run the app and load http://localhost:8080/person/index

## Versions

- grails: 3.3.9
- gorm: 6.1.11.RELEASE
- neo4j: 6.2.0.BUILD-SNAPSHOT

**Comment by jameskleeh** [comment]
@AmaliaMV The example app works as is. The response is immediate to `/person`

**Comment by AmaliaMV** [comment]
Hi @jameskleeh ...  I downloaded the project and ran it again on my computer. At first it did not work, but then it started to work. I don't why. Then, I increased the number of the data and I had the same problem again. I updated the https://github.com/AmaliaMV/neo4j-getAll

I did the request a couple of time, and I didn't have an answer.

![image](https://user-images.githubusercontent.com/5392638/51496527-e1181180-1d9e-11e9-8456-ce3c911d43af.png)

**Comment by jameskleeh** [comment]
@AmaliaMV I really have no idea why its inconsistently failing. Even with 10k it works sometimes. The code that is causing the issue is neo4j code so it may be their bug

**Comment by jameskleeh** [comment]
@graemerocher Can you take a look?

**Comment by graemerocher** [comment]
Had a look and it is indeed blocking at the driver level. There isn't much we can do about since it is a driver bug it seems. The best course of action at this point is to create an issue at https://github.com/neo4j/neo4j-java-driver/issues and see what the Neo4j folks say

**Comment by AmaliaMV** [comment]
@jameskleeh  @graemerocher . thanks guys! I updated neo4j-java-driver to 1.7.2, and that resolved the issue.
