### ISSUE TITLE
Running integration test are not using the right configuration

### ISSUE THREAD

**Issue by mburak** [grails/gorm-neo4j#2]
Trying to 
```run grails test-app :integration```

seems that it's not getting the right DataSource config. 
I have this configured on the environments section:

    test {
        grails {
            neo4j {
                type = "embedded"
                location = "${myEnv}/data"
                embedded {
                    options = [
                        'dbms.active_database': "graph_test.db",
                    ]
                }
            }
        }

but it's trying to use "remote" type and therefore not finding the right db and throwing the following exception:

```Caused by: org.neo4j.driver.v1.exceptions.ClientException: Unable to connect to 'localhost' on port 7687, ensure the database is running and that there is a working network connection to it.
	at org.neo4j.driver.internal.connector.socket.SocketClient.start(SocketClient.java:79)
	at org.neo4j.driver.internal.connector.socket.SocketConnection.<init>(SocketConnection.java:63)
	at org.neo4j.driver.internal.connector.socket.SocketConnector.connect(SocketConnector.java:52)
	at org.neo4j.driver.internal.pool.InternalConnectionPool$1.allocate(InternalConnectionPool.java:191)
	at org.neo4j.driver.internal.pool.InternalConnectionPool$1.allocate(InternalConnectionPool.java:180)
	at org.neo4j.driver.internal.pool.ThreadCachingPool.allocate(ThreadCachingPool.java:212)
	at org.neo4j.driver.internal.pool.ThreadCachingPool.acquireFromGlobal(ThreadCachingPool.java:164)
	at org.neo4j.driver.internal.pool.ThreadCachingPool.acquire(ThreadCachingPool.java:118)
	at org.neo4j.driver.internal.pool.InternalConnectionPool.acquire(InternalConnectionPool.java:109)
	at org.neo4j.driver.internal.InternalDriver.session(InternalDriver.java:53)
	at org.grails.datastore.gorm.neo4j.Neo4jDatastore.setupIndexing(Neo4jDatastore.java:385)
	at org.grails.datastore.gorm.neo4j.Neo4jDatastore.<init>(Neo4jDatastore.java:107)
	at org.grails.datastore.gorm.neo4j.Neo4jDatastore.<init>(Neo4jDatastore.java:217)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)```

**Comment by graemerocher** [comment]
I can't reproduce this personally. For integration tests to work I did have to disable the testing daemon:

      test: [maxMemory: 4096, minMemory: 2048, debug: false, maxPerm: 512, daemon:false],

Since Neo4j doesn't like being loaded in the daemon it seems. Other than that it worked as expected.

**Comment by mburak** [comment]
Ok, I changed a couple of things and tests are running now but getting this in a lot of them:

java.lang.NullPointerException: Cannot get property 'autowireCapableBeanFactory' on null object
	at org.grails.datastore.gorm.GormStaticApi.create(GormStaticApi.groovy:253)
	at org.grails.datastore.gorm.GormEntity$Trait$Helper.create(GormEntity.groovy:511)
	at grails.buildtestdata.DomainInstanceBuilder.build(DomainInstanceBuilder.groovy:136)
	at grails.buildtestdata.DomainInstanceBuilder.build(DomainInstanceBuilder.groovy:135)
	at grails.buildtestdata.BuildTestDataService.addBuildMethods_closure5(BuildTestDataService.groovy:45)
	at groovy.lang.Closure.call(Closure.java:426)
	at com.brinqa.platform.util.IntegrationTestUtils.createSupervisors(IntegrationTestUtils.groovy:562)
	at com.brinqa.platform.util.IntegrationTestUtils.createEmployees(IntegrationTestUtils.groovy:266)
	at com.brinqa.platform.analytics.AnalyticsControllerIntegrationSpec.setup(AnalyticsControllerIntegrationSpec.groovy:33)

It looks like applicationContext is null at that point?

**Comment by graemerocher** [comment]
GORM 6 has been separated from Spring and the application context so it is quite possible that this could be an issue. Please provide an example that reproduces the issue.

**Comment by mburak** [comment]
You can use the project at https://github.com/mburak/neo4j-app and run ClubControllerIntegrationSpec.
