### ISSUE TITLE
Getting UnexpectedRollbackException on integration tests (on latest 6.0.3 snapshot)

### ISSUE THREAD

**Issue by mburak** [grails/gorm-neo4j#24]
When running the integration tests we are getting this:

```
org.springframework.transaction.UnexpectedRollbackException: Rollback exception, originated at (org.grails.datastore.gorm.neo4j.Neo4jDatastoreTransactionManager@5517e36b) null; nested exception is java.lang.NullPointerException
	at org.codehaus.groovy.grails.transaction.ChainedTransactionManager.rollback(ChainedTransactionManager.java:208)
	at org.codehaus.groovy.grails.test.support.GrailsTestTransactionInterceptor.destroy_closure2(GrailsTestTransactionInterceptor.groovy:85)
	at groovy.lang.Closure.call(Closure.java:426)
	at org.codehaus.groovy.grails.test.support.GrailsTestTransactionInterceptor.destroy(GrailsTestTransactionInterceptor.groovy:83)
	at grails.test.spock.IntegrationSpec.destroyTransaction(IntegrationSpec.groovy:89)
	at grails.test.spock.IntegrationSpec.cleanup(IntegrationSpec.groovy:70)
Caused by: java.lang.NullPointerException
	at org.grails.datastore.mapping.transactions.DatastoreTransactionManager.doRollback(DatastoreTransactionManager.java:179)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processRollback(AbstractPlatformTransactionManager.java:849)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.rollback(AbstractPlatformTransactionManager.java:826)
	at org.codehaus.groovy.grails.transaction.MultiTransactionStatus.rollback(MultiTransactionStatus.java:82)
	at org.codehaus.groovy.grails.transaction.ChainedTransactionManager.rollback(ChainedTransactionManager.java:191)
	... 5 more
```

**Comment by mburak** [comment]
You can see this behavior in https://github.com/mburak/neo4j-app, executing LeagueControllerIntegrationSpec. When a test throws an exception, it's throwing that exception above and the next tests fail.
