### ISSUE TITLE
Unit Tests - Relationship Support for Self Referential Many to many

### ISSUE THREAD

**Issue by yellek** [grails/gorm-neo4j#278]
From https://stackoverflow.com/questions/69139054/self-referential-many-to-many-using-relationship-classes-with-grails-gorm-and-n

I have a Grails domain class with a self referential many-to-many:

class ModelElement {

    String name
    String elementType
    String modelType
    String description
    String toolIdentifier
    
    
    static hasMany = [
        relatedFrom: ModelElement,
        relatedTo: ModelElement
    ]
    
    static mappedBy = [
        relatedFrom: 'relatedTo',
        relatedTo: 'relatedFrom'
    ]
    
    
    static mapping = {
        id generator: 'assigned',
        name: 'toolIdentifier'
    }
    
    static constraints = {
        description nullable:true
    }
}
I want to map the relationship in neo4j using a relationship class like the following:

    import grails.neo4j.Relationship

class ModelRelationship implements Relationship<ModelElement, ModelElement> {

    String name
    String relationshipType
    String modelType
    String description
    String toolIdentifier

    static constraints = {
        name nullable:true
        description nullable:true
    }
}
When I try this code:

            def element1 = new ModelElement(
                name: 'Test Name 1',
                modelType: "Archimate",
                elementType: "Assessment",
                toolIdentifier: 'A123').save()
            def element2 = new ModelElement(
                name: 'Test Name 2',
                modelType: "Archimate",
                elementType: "Assessment",
                toolIdentifier: 'Z456').save()
            def relationship = new ModelRelationship(
                modelType: "Archimate",
                relationshipType: "Association",
                toolIdentifier: 'Z456',
                from: element1,
                to: element2).save()
I get the exception shown below. I have also tried changing the relatedFrom and relatedTo properties to type ModelRelationship however that creates a mapping error for mappedBy because those properties don't exist on ModelRelationship.

Any ideas?
```
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'me.yellek.adtf.model.ModelRelationship' with class 'org.grails.datastore.mapping.keyvalue.mapping.config.KeyValuePersistentEntity' to class 'org.grails.datastore.gorm.neo4j.RelationshipPersistentEntity'
    at grails.neo4j.Relationship$Trait$Helper.type(Relationship.groovy:44)
    at grails.neo4j.Relationship$Trait$Helper.getType(Relationship.groovy:53)
    at grails.neo4j.Relationship$Trait$Helper.hashCode(Relationship.groovy:84)
    at java.base/java.util.HashMap.hash(HashMap.java:340)
    at java.base/java.util.HashMap.put(HashMap.java:612)
    at java.base/java.util.HashSet.add(HashSet.java:221)
    at grails.gorm.validation.PersistentEntityValidator.validate(PersistentEntityValidator.groovy:68)
    at org.grails.datastore.gorm.GormValidationApi.doValidate(GormValidationApi.groovy:124)
    at org.grails.datastore.gorm.GormValidationApi.validate(GormValidationApi.groovy:153)
    at org.grails.datastore.gorm.GormValidateable$Trait$Helper.validate(GormValidateable.groovy:71)
    at org.grails.datastore.gorm.GormInstanceApi.doSave(GormInstanceApi.groovy:333)
    at org.grails.datastore.gorm.GormInstanceApi.save_closure5(GormInstanceApi.groovy:180)
    at groovy.lang.Closure.call(Closure.java:412)
    at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:319)
    at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:40)
    at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:179)
    at org.grails.datastore.gorm.GormInstanceApi.save(GormInstanceApi.groovy:119)
    at org.grails.datastore.gorm.GormEntity$Trait$Helper.save(GormEntity.groovy:100)
    at me.yellek.adtf.model.ModelRelationshipSpec.test basic relationship mapping(ModelRelationshipSpec.groovy:30)
```

**Comment by puneetbehl** [comment]
Coudl you please verifty if it works in an IntegrationTest?

**Comment by yellek** [comment]
I can confirm it does work in integration test.

**Comment by puneetbehl** [comment]
It fails because Grails unit tests uses  `KeyValueMappingContext` instead of `Neo4jMappingContext`. I think you could extend  [Neo4jSpec.groovy](https://github.com/grails/gorm-neo4j/blob/master/grails-plugin/src/main/groovy/grails/test/neo4j/Neo4jSpec.groovy). Otherwise, you may need to write integration test.

**Comment by yellek** [comment]
So shouldn't Neo4j be supported by Grails unit tests? Is this now a feature request?

**Comment by puneetbehl** [comment]
No, unit tests are setup with basic `SimpleMapDatastore` designed for basic scenarios but if you want to tests things related to Neo4J then you need to initialize `Neo4jMappingContext` or write integration tests. I think `Neo4jSpec.groovy` should provide you ability to test the above.
