### ISSUE TITLE
Unit tests failing after upgrade to 6.1

### ISSUE THREAD

**Issue by mburak** [grails/gorm-neo4j#40]
Getting the following exception in many unit tests. It was working fine on 6.0.9. Is there anything that we need to change in tests? 

```
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'org.grails.datastore.gorm.GormStaticApi@7d3de280' with class 'org.grails.datastore.gorm.GormStaticApi' to class 'org.grails.datastore.gorm.neo4j.api.Neo4jGormStaticApi'
	at grails.neo4j.Neo4jEntity$Trait$Helper.find(Neo4jEntity.groovy:243)
	at com.brinqa.platform.core.model.Attribute.getDataModel(Attribute.groovy:190)
	at com.brinqa.platform.core.model.Attribute._clinit__closure6$_closure7(Attribute.groovy:83)
	at groovy.lang.Closure.call(Closure.java:414)
	at org.grails.validation.ValidatorConstraint.processValidate(ValidatorConstraint.java:87)
	at grails.validation.AbstractConstraint.validate(AbstractConstraint.java:107)
	at grails.validation.ConstrainedProperty.validate(ConstrainedProperty.java:979)
	at org.grails.validation.GrailsDomainClassValidator.validatePropertyWithConstraint(GrailsDomainClassValidator.java:206)
	at org.grails.validation.GrailsDomainClassValidator.validate(GrailsDomainClassValidator.java:81)
	at org.grails.datastore.gorm.GormValidationApi.doValidate(GormValidationApi.groovy:116)
	at org.grails.datastore.gorm.GormValidationApi.validate(GormValidationApi.groovy:197)
	at org.grails.datastore.gorm.GormValidateable$Trait$Helper.validate(GormValidateable.groovy:97)
	at com.brinqa.platform.core.model.DataModel$__clinit__closure23.closure25$_closure26(DataModel.groovy:98)
	at com.brinqa.platform.core.model.DataModel._clinit__closure23$_closure25(DataModel.groovy:97)
	at groovy.lang.Closure.call(Closure.java:414)
	at org.grails.validation.ValidatorConstraint.processValidate(ValidatorConstraint.java:87)
	at grails.validation.AbstractConstraint.validate(AbstractConstraint.java:107)
	at grails.validation.ConstrainedProperty.validate(ConstrainedProperty.java:979)
	at org.grails.validation.GrailsDomainClassValidator.validatePropertyWithConstraint(GrailsDomainClassValidator.java:206)
	at org.grails.validation.GrailsDomainClassValidator.validate(GrailsDomainClassValidator.java:81)
	at org.grails.datastore.gorm.GormValidationApi.doValidate(GormValidationApi.groovy:116)
	at org.grails.datastore.gorm.GormValidationApi.validate(GormValidationApi.groovy:197)
	at org.grails.datastore.gorm.GormValidateable$Trait$Helper.validate(GormValidateable.groovy:97)
	at com.brinqa.platform.analytics.AnalyticsControllerSpec.createDataModels(AnalyticsControllerSpec.groovy:299)
	at com.brinqa.platform.analytics.AnalyticsControllerSpec.test execute (age transformation)(AnalyticsControllerSpec.groovy:90)
```

**Comment by graemerocher** [comment]
You seem to be using a Cypher query since line 243 of `Neo4jEntity` executes a cypher query. Since unit tests do not support string-based queries like Cypher, this must have failing before, just with a different error message.

Either way any interaction with Cypher would require an integration test. so I see this as a minor issue that should be changed in your unit tests.

**Comment by mburak** [comment]
Yeah, I see the issue. We were mocking that find method but it changed the signature so it wasn't using it. Thanks.
