### ISSUE TITLE
DataIntegrityViolationException while trying to get an association's property which is null

### ISSUE THREAD

**Issue by mburak** [grails/gorm-neo4j#47]
Having this structure:
```
class Player extends AbstractGraphDomain {

    String name
    Application application

    static mapping = {
        dynamicAssociations true
    }

    String getParentAppName() {
        if (application?.parent) {
            return application.parent.name
        }
        
        return null
    }
}

class Application extends AbstractGraphDomain {

    String name
    String appVersion
    Application parent

    static constraints = {
        appVersion nullable: true
        type nullable: true, bindable: true
        parent nullable: true
    }

}
```
When trying to check if a player's application has parent (which is another application) and this parent is null,
```
        Player player = Player.findByName("player1")
        String app = player.getParentAppName()
```
 it's throwing this exception:
```
java.lang.reflect.InvocationTargetException: null
        at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
        at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
        at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.dao.DataIntegrityViolationException: Proxy for [core.Application] for association [core.Application] could not be initialized
        at org.grails.datastore.mapping.proxy.AssociationQueryProxyHandler.resolveDelegate(AssociationQueryProxyHandler.java:83)
        at org.grails.datastore.mapping.proxy.GroovyObjectMethodHandler.resolveDelegateAndGetProperty(GroovyObjectMethodHandler.java:59)
        at org.grails.datastore.mapping.proxy.GroovyObjectMethodHandler.getProperty(GroovyObjectMethodHandler.java:52)
        at org.grails.datastore.mapping.proxy.GroovyObjectMethodHandler.handleInvocation(GroovyObjectMethodHandler.java:167)
        at org.grails.datastore.mapping.proxy.EntityProxyMethodHandler.handleInvocation(EntityProxyMethodHandler.java:76)
        at org.grails.datastore.mapping.proxy.GroovyObjectMethodHandler.invoke(GroovyObjectMethodHandler.java:141)
        at core.Player.getParentAppName(Player.groovy:20)
        at core.PlayerController.$tt__updatePlayer3(PlayerController.groovy:49)
        at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:96)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
        ... 14 common frames omitted
```

You can reproduce this by downloading: https://github.com/mburak/sampleapp and checking out branch 'dup-assoc'
1. Start up the application on an empty db.
2. Call rest api url: http://localhost:8080/player/updatePlayer3

**Comment by graemerocher** [comment]
This is working as documented. See http://gorm.grails.org/latest/neo4j/manual/index.html#lazyLoading

Quote:

> However if you were to access the league association and it were null you would get an exception.

**Comment by mburak** [comment]
But isn't that only if you set lazy: true for the relationship?

**Comment by graemerocher** [comment]
The `Application` -> `parent` association is a circular relationship to the same entity (essentially a tree). This has to be `lazy:true` by default since otherwise the result would be an infinite loop. 

So the documentation applies to circular many-to-ones or trees too. Feel free to submit a pull request for the documentation if you wish to clarify. 

See https://github.com/grails/gorm-neo4j/blob/master/grails-datastore-gorm-neo4j/src/main/groovy/org/grails/datastore/gorm/neo4j/engine/Neo4jQuery.groovy#L440

**Comment by mburak** [comment]
I see. How can we avoid this exception when we have this kind of structure?

**Comment by mburak** [comment]
So in this case, it fixes it if I put _lazy: false_ in Player's application property. I thought that what I needed to make _lazy: false_ was the parent property inside the Application class but that didn't make any change.

**Comment by mburak** [comment]
One more issue with this is that having a class that has a dynamic association to the same class cannot be configured as lazy: false because is dynamic and we get the exception everytime we have this kind of relationships. Can you think of anything that would help solve that?

**Comment by AmaliaMV** [comment]
Hi, I have a similiar problem, but I don't have a  circular relationship. This is the code:

```
class Person extends BaseGraphDomain {
    String name
}

class Club extends BaseGraphDomain {
    String name
}

class PrivateClub extends Club {
    Person person
    static constraints = {
        person nullable: true
    }
}
```

Here is the initial loading data
```
Club club = Club.findByName('Boca Jrs')

if (!club) {
    club = new PrivateClub(name: 'Boca Jrs')
    club.person = new Person(name: 'Canelo').save()
    club.save()
}

club = Club.findByName('River')

if (!club) {
    club = new PrivateClub(name: 'River')
    club.save()
}
```

So, Boca Club has a person, but River Club doesn't. 

This is my controller:
```
class ApplicationController {

    def index() {

        Club club1 = Club.findByName('Boca Jrs')
        Club club2 = Club.findByName('River') // here I have the DataIntegrityViolationException

        [club1: club1, club2: club2]
    }

  
    def indexOK() {

        Club club1 = Club.findByName('Boca Jrs')
        Club club2 = PrivateClub.findByName('River') // here is OK

        render view:'index', model: [club1: club1, club2: club2]
    }
}

```

The difference is in index() I use Club class and indexOK() I use PrivateClub to get River Club. With the second one, I don't have the exception.

Link: https://github.com/AmaliaMV/neo4j-DataIntegrityViolationException
To make test: 

- http://localhost:8080  (it's not working); 

- http://localhost:8080/ok  (works)

**Comment by jameskleeh** [comment]
This is caused by the difference in the query that gets generated

PrivateClub:
```
QUERY Cypher [MATCH (n:PrivateClub) WHERE ( n.name={1} ) 
OPTIONAL MATCH(n)-[r0:PERSON]->(personNode:Person) WITH n, collect(DISTINCT ID(personNode)) as personIds RETURN n as data
```

Club:
`QUERY Cypher [MATCH (n:Club) WHERE ( n.name={1} ) RETURN n as data`

Because the `PrivateClub` query includes that optional match, a proxy is never created. @graemerocher As best I can tell, the way to fix this would be to loop through subclass assocations here as well: https://github.com/grails/gorm-neo4j/blob/master/grails-datastore-gorm-neo4j/src/main/groovy/org/grails/datastore/gorm/neo4j/engine/Neo4jQuery.groovy#L420. Thoughts?

**Comment by AmaliaMV** [comment]
Hi @jameskleeh ,

When I tested the fix on the sample app, all works fine. But when I tested in our app, I had an exception. I updated the example to reproduce the new error.


When I have this class with an attribute (in this case, User) which can be nullable:

```
abstract class BaseGraphDomain {

    static mapWith = "neo4j"

    User createBy   <-- new 
    User updateBy  <-- new 

    Date dateCreated
    Date lastUpdated

    static constraints = {
        createBy nullable: true    <-- new 
        updateBy nullable: true  <-- new 
    }
}
```

I have the next  exception:

```
org.neo4j.driver.v1.exceptions.ClientException: Multiple result columns with the same name are not supported (line 4, column 62 (offset: 329))
"OPTIONAL MATCH(n)-[r2:CREATEBY]->(createByNode:User) WITH n, createByIds, personIds, collect(DISTINCT ID(createByNode)) as createByIds RETURN n as data"
                                                              ^
        at org.neo4j.driver.internal.util.ErrorUtil.newNeo4jError(ErrorUtil.java:62)
        at org.neo4j.driver.internal.async.inbound.InboundMessageDispatcher.handleFailureMessage(InboundMessageDispatcher.java:138)
        at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.unpackFailureMessage(PackStreamMessageFormatV1.java:431)
        at org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.read(PackStreamMessageFormatV1.java:395)
        at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:83)
        at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:35)
        at org.neo4j.driver.internal.shaded.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at org.neo4j.driver.internal.async.inbound.MessageDecoder.channelRead(MessageDecoder.java:40)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
        at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
        at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at org.neo4j.driver.internal.shaded.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1336)
        at org.neo4j.driver.internal.shaded.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1127)
        at org.neo4j.driver.internal.shaded.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1162)
        at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
        at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
        at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
        at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)
```

Here is the link: https://github.com/AmaliaMV/neo4j-DataIntegrityViolationException

I am using  neo4j version: 6.2.0.BUILD-SNAPSHOT.

**Comment by AmaliaMV** [comment]
Hi @jameskleeh 

I still have the same problem when I have a hasToMany relationship like this:

```
class Club extends BaseGraphDomain {

    static hasMany = [players: Player]

    String name

    static constraints = {
        name nullable: false, blank: false, unique: true
    }
}

class Player extends BaseGraphDomain {

    String name

    static belongsTo = [Club]
}

abstract class BaseGraphDomain {

    static mapWith = "neo4j"

    User createBy
    User updateBy

    Date dateCreated
    Date lastUpdated

    static constraints = {
        createBy nullable: true
        updateBy nullable: true
    }
}
```

If I ask for a Club:

```
Club club2 = Club.findByName('SomeClubWithPlayers')
Player player2 = club2.players[0]  // <-- in the debug you can see those messages:         
                                    // Method threw 'org.springframework.dao.DataIntegrityViolationException' exception. Cannot evaluate neo4jSample.core.User_$$_jvst40e_2.toString()
                                    // Method threw 'org.springframework.dao.DataIntegrityViolationException' exception. Cannot evaluate neo4jSample.core.User_$$_jvst40e_2.toString()

```

In this case,  createBy and updateBy properties of Player can be nullable.

I updated the repo: https://github.com/AmaliaMV/neo4j-DataIntegrityViolationException

**Comment by jameskleeh** [comment]
@AmaliaMV Looks like a separate issue. I'll look into it

**Comment by AmaliaMV** [comment]
@jameskleeh ... Oh! ok. You are right, here the problem is different. 

I am seening the neo4j queries. When I ask for the Club, the query is:

```
QUERY Cypher [MATCH (n:Club) WHERE ( n.name={1} ) 
OPTIONAL MATCH(n)-[r0:CREATEBY]->(createByNode:User) WITH n, collect(DISTINCT ID(createByNode)) as createByIds 
OPTIONAL MATCH(n)-[r2:PRESIDENT]->(presidentNode:President) WITH n, createByIds, collect(DISTINCT ID(presidentNode)) as presidentIds 
OPTIONAL MATCH(n)-[r3:UPDATEBY]->(updateByNode:User) WITH n, createByIds, presidentIds, collect(DISTINCT ID(updateByNode)) as updateByIds RETURN n as data
, createByIds, presidentIds, updateByIds ] for params [[1:River]]
```
But, players is a hasMany property and as your documentation says  there are a second query to load the player (in this case):

```
QUERY Cypher [MATCH (from:PrivateClub)-[:PLAYERS]->(to:Player) WHERE ID(from) = {id} RETURN to as data] for params [[id:264550]]
```

The problem I am seeing here is that query doesn't have the "OPTIONAL MATCH" for the fields which could be nullable.
