### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.server.SessionManager while running unit test

### ISSUE THREAD

**Issue by sdelamo** [grails/gorm-neo4j#57]
I am getting  the next error: 

```
org.grails.datastore.mapping.model.DatastoreConfigurationException: Unable to start embedded Neo4j server: org/eclipse/jetty/server/SessionManager
	at org.grails.datastore.gorm.neo4j.connections.Neo4jConnectionSourceFactory.create(Neo4jConnectionSourceFactory.java:81)
	at org.grails.datastore.gorm.neo4j.connections.Neo4jConnectionSourceFactory.create(Neo4jConnectionSourceFactory.java:30)
	at org.grails.datastore.mapping.core.connections.AbstractConnectionSourceFactory.create(AbstractConnectionSourceFactory.java:64)
	at org.grails.datastore.mapping.core.connections.AbstractConnectionSourceFactory.create(AbstractConnectionSourceFactory.java:52)
	at org.grails.datastore.mapping.core.connections.ConnectionSourcesInitializer.create(ConnectionSourcesInitializer.groovy:24)
	at org.grails.datastore.gorm.neo4j.Neo4jDatastore.<init>(Neo4jDatastore.java:250)
	at org.grails.datastore.gorm.neo4j.Neo4jDatastore.<init>(Neo4jDatastore.java:272)
	at org.grails.datastore.gorm.neo4j.Neo4jDatastore.<init>(Neo4jDatastore.java:282)
	at org.grails.datastore.gorm.neo4j.Neo4jDatastore.<init>(Neo4jDatastore.java:320)
	at neo4j.movies.MovieServiceSpec.$spock_initializeSharedFields(MovieServiceSpec.groovy:12)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/jetty/server/SessionManager
	at org.neo4j.server.CommunityNeoServer.createWebServer(CommunityNeoServer.java:89)
	at org.neo4j.server.AbstractNeoServer.init(AbstractNeoServer.java:181)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:196)
	at org.neo4j.harness.internal.InProcessServerControls.start(InProcessServerControls.java:72)
	at org.neo4j.harness.internal.AbstractInProcessServerBuilder.newServer(AbstractInProcessServerBuilder.java:137)
	at org.grails.datastore.gorm.neo4j.util.EmbeddedNeo4jServer.start(EmbeddedNeo4jServer.java:175)
	at org.grails.datastore.gorm.neo4j.util.EmbeddedNeo4jServer.start(EmbeddedNeo4jServer.java:88)
	at org.grails.datastore.gorm.neo4j.util.EmbeddedNeo4jServer.attemptStartServer(EmbeddedNeo4jServer.java:185)
	at org.grails.datastore.gorm.neo4j.util.EmbeddedNeo4jServer.start(EmbeddedNeo4jServer.java:53)
	at org.grails.datastore.gorm.neo4j.connections.Neo4jConnectionSourceFactory.create(Neo4jConnectionSourceFactory.java:75)
	... 9 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.server.SessionManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more
```

while running the next Unit test in a Grails 3.3.0 app:

```
package neo4j.movies

import grails.gorm.transactions.Rollback
import org.grails.datastore.gorm.neo4j.Neo4jDatastore
import spock.lang.AutoCleanup
import spock.lang.Shared
import spock.lang.Specification

@SuppressWarnings(['MethodName', 'DuplicateNumberLiteral', 'UnnecessaryGetter', 'TrailingWhitespace'])
class MovieServiceSpec extends Specification {

    @Shared @AutoCleanup Neo4jDatastore datastore = new Neo4jDatastore(getClass().getPackage())
    
    MovieService service =  datastore.getService(MovieService)
    
    @Rollback
    void 'Test search movies'() {
        given:
        new Movie(title: 'The Matrix', tagline: 'Free your mind', released: 1999).save(flush:true)

        expect: 'to find results'
        service.search('Matr')
        service.search('The')
        !service.search('The Wrestler')
    }
}
```
I have the next rest runtime dependency

`testRuntime "org.neo4j.test:neo4j-harness:3.1.2"`

Other persons have reported similar [failures while running integration tests with Spring Boot 1.5 and Neo4j](https://stackoverflow.com/questions/42227676/spring-boot-integration-test-fails-with-neo4j)

## Example repository

The `complete` folder in the next repository contains a Grails 3 application with an `@Ignored` test which demonstrates this issue. 

https://github.com/grails-guides/neo4j-movies

**Comment by graemerocher** [comment]
This is a Jetty version conflict between the default version of Jetty in Spring Boot and the version required by the Neo4j server when run embedded.

You can workaround it by specifying the following in `build.gradle`:

```groovy
ext['jetty.version'] = '9.2.9.v20150224'
```
